module.exports = {
  apps: [
    {
      name: "zhengche-platform",
      script: "backend/server.js",
      cwd: __dirname + "/..",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: process.env.PORT || "3000",
        ADMIN_USER: process.env.ADMIN_USER || "admin",
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || "change-this-password",
        TOKEN_SECRET: process.env.TOKEN_SECRET || "",
        CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS || process.env.APP_ORIGIN || "",
        SESSION_TTL_MS: process.env.SESSION_TTL_MS || "86400000",
        LOGIN_RATE_LIMIT_WINDOW_MS: process.env.LOGIN_RATE_LIMIT_WINDOW_MS || "900000",
        LOGIN_RATE_LIMIT_MAX_ATTEMPTS: process.env.LOGIN_RATE_LIMIT_MAX_ATTEMPTS || "5",
        LOGIN_RATE_LIMIT_LOCK_MS: process.env.LOGIN_RATE_LIMIT_LOCK_MS || "900000",
        AI_PROVIDER: process.env.AI_PROVIDER || "",
        AI_CHAT_RATE_LIMIT_WINDOW_MS: process.env.AI_CHAT_RATE_LIMIT_WINDOW_MS || "60000",
        AI_CHAT_RATE_LIMIT_MAX_REQUESTS: process.env.AI_CHAT_RATE_LIMIT_MAX_REQUESTS || "20",
        DEEPSEEK_API_KEY: process.env.DEEPSEEK_API_KEY || "",
        DEEPSEEK_BASE_URL: process.env.DEEPSEEK_BASE_URL || "https://api.deepseek.com",
        DEEPSEEK_MODEL: process.env.DEEPSEEK_MODEL || "deepseek-v4-flash",
        DEEPSEEK_THINKING: process.env.DEEPSEEK_THINKING || "disabled",
        DEEPSEEK_TIMEOUT_MS: process.env.DEEPSEEK_TIMEOUT_MS || "8000",
        DEEPSEEK_MAX_TOKENS: process.env.DEEPSEEK_MAX_TOKENS || "800",
        DB_DRIVER: process.env.DB_DRIVER || "json",
        MYSQL_HOST: process.env.MYSQL_HOST || "127.0.0.1",
        MYSQL_PORT: process.env.MYSQL_PORT || "3306",
        MYSQL_DATABASE: process.env.MYSQL_DATABASE || "vehicle_export",
        MYSQL_USER: process.env.MYSQL_USER || "vehicle_export",
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD || "",
        DATABASE_URL: process.env.DATABASE_URL || "",
        OSS_ENABLED: process.env.OSS_ENABLED || "false",
        OSS_BUCKET: process.env.OSS_BUCKET || "",
        OSS_REGION: process.env.OSS_REGION || "",
        OSS_ENDPOINT: process.env.OSS_ENDPOINT || "",
        OSS_PUBLIC_BASE_URL: process.env.OSS_PUBLIC_BASE_URL || "",
        OSS_UPLOAD_PREFIX: process.env.OSS_UPLOAD_PREFIX || "uploads/",
        OSS_PUBLIC_READ: process.env.OSS_PUBLIC_READ || "false",
        OSS_SIGNED_URL_TTL_SECONDS: process.env.OSS_SIGNED_URL_TTL_SECONDS || "3600",
        OSS_ACCESS_KEY_ID: process.env.OSS_ACCESS_KEY_ID || "",
        OSS_ACCESS_KEY_SECRET: process.env.OSS_ACCESS_KEY_SECRET || "",
      },
      max_memory_restart: "300M",
      error_file: "logs/pm2-error.log",
      out_file: "logs/pm2-out.log",
      time: true,
    },
  ],
};
